export * from './Main.component';
export * from './Prayers.component';
export * from './Services.component';
export * from './Contact.component';
export * from './Pillars.component';
export * from './Member.component';
export * from './Events.component';
export * from './About.component';
export * from './Khutbe.component';
